[package]
name = "r_trait"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "parse"
path = "src/parse.rs"

[[bin]]
name = "write"
path = "src/write.rs"

[dependencies]
regex = "1.5"
